# Generated by Django 5.1.1 on 2024-09-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_bus_faciilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='faciilities',
            new_name='facilities',
        ),
    ]
