# Generated by Django 5.1.1 on 2024-10-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_alter_ticket_options_alter_ticket_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to='???'),
        ),
    ]
